### ISSUE TITLE
兼容antd 5.0

### ISSUE THREAD

**Issue by zhengchalei** [mkgrow/cron-react#2]

**Comment by zhengchalei** [comment]
'~antd/es/style/themes/variable' wasn't found.

**Comment by mkgrow** [comment]
> '~antd/es/style/themes/variable' wasn't found.

引用的样式问题，less里边已经删除

**Comment by mkgrow** [comment]
> '~antd/es/style/themes/variable' wasn't found.

重新装下试试

**Comment by zhengchalei** [comment]
Can't resolve 'antd/es/time-picker/style
Can't resolve 'antd/lib/locale-provider/zh_CN'
Can't resolve 'antd/es/time-picker/style'
，要不你测一下 antd5
